version: '3'
services:
    db:
        image: mysql
        ports: 
            - 3309:3306
        environment: 
            MYSQL_DATABASE: lblms
            MYSQL_USER: lblms
            MYSQL_PASSWORD: lblms
            MYSQL_ROOT_PASSWORD: lblms
    web: 
            build: .
            depends_on: 
                - db
            environment: 
                HOSTNAME: db
            ports: 
                - 8080:8080