version: '3.7'
services:
    web: 
        build: .
        ports: 
            - 8080:8080
    db:
        image: mysql:latest
        ports: 
            - 3309:3306
        environment: 
            MYSQL_DATABASE: lblms
            MYSQL_USER: user1
            MYSQL_PASSWORD: password123
            MYSQL_ROOT_PASSWORD: root